apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubernetes.io/change-cause: kubectl set image deployment helloworld helloworld=rajuankilla20/helloworld:0.0.2-RELEASE
      --record=true
  creationTimestamp: "2020-08-10T14:17:45Z"
  generation: 6
  labels:
    app: helloworld
  name: helloworld
  namespace: default
  resourceVersion: "1325643"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/helloworld
  uid: 1ad60760-f273-47cf-8cbc-f95f6cecedad
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld
    spec:
      containers:
      - image: rajuankilla20/helloworld:0.0.2-RELEASE
        imagePullPolicy: IfNotPresent
        name: helloworld
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-08-10T14:23:13Z"
    lastUpdateTime: "2020-08-10T14:23:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-08-10T14:17:45Z"
    lastUpdateTime: "2020-08-10T14:59:40Z"
    message: ReplicaSet "helloworld-7db96f84cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
