apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: rajuankilla20/helloworld:0.0.2-RELEASE
        imagePullPolicy: IfNotPresent
        name: helloworld
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: default
spec:
  ports:
    - nodePort: 31758
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: helloworld
  sessionAffinity: None
  type: LoadBalancer